services:
  # Backend service
  - type: web
    name: msg-dashboard-api
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///messages.db
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0

  # Frontend service
  - type: web
    name: msg-dashboard-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        fromService:
          name: msg-dashboard-api
          type: web
          property: url 