services:
  # Backend service
  - type: web
    name: msg-dashboard-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        value: sqlite:///messages.db
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0

  # Frontend service as static site
  - type: static
    name: msg-dashboard-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 14.17.0
      - key: REACT_APP_API_URL
        value: https://msg-dashboard-api.onrender.com 